on:
  # Trigger the workflow on push to 'main' branch
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Install Dependencies
      run: npm ci
    - name: Prettify Code
      run: npm run format
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Install Dependencies
      run: npm ci
    - name: Lint Code
      run: npm run lint
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        
  build:
    needs: [format, lint]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Install Dependencies
      run: npm ci
    - name: Build Code
      run: npm run build
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions

  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - name: Install Dependencies
      run: npm ci
    - name: Build Code
      run: npm run docs
    - name: Commit any changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions